### ISSUE TITLE
PatchOperation does not handle multiple file removals/deletions

### ISSUE THREAD

**Issue by AterAnimAvis** [TheCBProject/DiffPatch#4]
[Test Case](https://github.com/AterAnimAvis/DiffPatch/commit/a67be5267710c2ea839c9b86618d874e41c479a3)
[Relevant Stack Trace](https://gist.github.com/AterAnimAvis/7408c898b484f4aa6692914797105f60)

Description:
https://github.com/TheCBProject/DiffPatch/blob/8affab08a7e9a98ab52e675adc357af8275e9017/src/main/java/codechicken/diffpatch/cli/PatchOperation.java#L261-L268
Current logic for a [removal patch](https://github.com/AterAnimAvis/DiffPatch/blob/a67be5267710c2ea839c9b86618d874e41c479a3/src/test/resources/data/patches/A.txt.patch) falls through to `e.patchedPath` which will always be `/dev/null`.
`Collectors#toMap` will then throw an exception due to the duplicated file keys.

One potential solution:
[Default to `name` if the `patchedPath` is *either* `null` or `/dev/null`](https://github.com/AterAnimAvis/DiffPatch/commit/06d62fbe6f5e0639283dd7bab8c243b8e04e0352#diff-9933d20addeea5597adedc3c9c14fc118993c0df34a5409f0fad4c694dc48d15L261-R261)
[Fixing that causes a secondary issue where the target files are still created with empty contents](https://github.com/AterAnimAvis/DiffPatch/commit/06d62fbe6f5e0639283dd7bab8c243b8e04e0352#diff-9933d20addeea5597adedc3c9c14fc118993c0df34a5409f0fad4c694dc48d15L356-R356)

**Comment by covers1624** [comment]
Interesting, this was never considered when I was writing the cli interface.

I suppose it fails similarly when creating files with patches?

**Comment by AterAnimAvis** [comment]
Looks like it doesn't actually work at all:
`Missing patch target for A.txt.patch`

[Test Case](https://github.com/AterAnimAvis/DiffPatch/commit/e4a4ef1b141fd4c154d24972d369fed5f7263488)

**Comment by Chicken-Bones** [comment]
I didn't know removal patches were a thing, but this excites me. We should support them when diffing too :)

**Comment by AterAnimAvis** [comment]
It already does in terms of cli, these patches where generated by `DiffOperation`.
